# 개요

- 케라스는 많은 사람들이 손쉽게 딥러닝을 할 수 있도록 다양한 엔진(플랫폼)위에서 딥러닝 모델을 구현할 수 있는 API이다
- 어떤 엔진 사용하더라도 그 위에서 구현된 코드는 동일하다
- 2017
  - Tensorflow Dev SUMMIT 2017에서 케라스와 텐서플로우의 통합을 발표
- tf.keras를 통해서 케라스를 사용
- 텐서플로우 코어 레이어와 케라스 레이어는 동일
- 순수 텐서플로우 기능과 케라스 기능이 쉽게 어울려서 사용할 수 있다
- 모델 정의는 케라스의 고차원 API를 이용하여 구현

In [0]:
import keras
%tensorflow_version 1.x

# 간단한 데이터로 기본 루틴

In [0]:
import numpy as np

In [0]:
# 데이터 준비
x=np.array([0,1,2,3,4])
# 인공신경망:딥러닝의 알고리즘
# W(가중치) -> 2
# b(편향) -> 1
y=x*2+1
x,y

(array([0, 1, 2, 3, 4]), array([1, 3, 5, 7, 9]))

In [0]:
# 인공신경망 만들기 -> 층을 쌓는다
# 1. 인공신경망 모델을 만들기 시작했음을 파이썬 프로세스에게 알린다
model=keras.models.Sequential()

In [0]:
# 2. 레이어 추가 -> 층을 쌓는다
# 입력 노드는 한개, 가중치도 한개인 선형 처리 계층
model.add(keras.layers.Dense(1, input_shape=(1,)))

In [0]:
#3. 학습단계 설정
model.compile('SGD','mse')

In [0]:
# 훈련
#훈련데이터, 답 삽입
#epochs:인공신경망이 한번 학습을 수행할때 사용된 데이터
#verbose:로그, 학습진행사항 표시. 0이면 미표시
model.fit(x[:2], y[:2],epochs=1000,verbose=0)

In [0]:
#예측평가
model.predict(x[2:]).flatten()

array([5.0017376, 7.002995 , 9.004252 ], dtype=float32)

In [0]:
y[2:]

array([5, 7, 9])